name: Hprofile actions by anand 
on: workflow_dispatch

jobs: 
  Testing:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout Code
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Maven test
        run: mvn test

      - name: Run Checkstyle
        run: mvn checkstyle:checkstyle

      # setup java 11 to be default (sonar-scanner requirement as of 5.x)
      - name: Set Java 11
        uses: actions/setup-java@v3
        with:
         distribution: 'temurin' 
         java-version: '11'

      # Step 4: Setup SonarQube
      - name: Setup SonarQube
        uses: warchant/setup-sonar-scanner@v7

      # Step 5: Run SonarQube Analysis
      - name: SonarQube Scan
        run: sonar-scanner
            -Dsonar.host.url=${{ secrets.SONAR_URL }} 
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} 
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} 
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} 
            -Dsonar.sources=src/
            -Dsonar.junit.reportPaths=target/surefire-reports/
            -Dsonar.jacoco.reportPaths=target/jacoco.exec
            -Dsonar.java.checkstyle.reportsPaths=target/checkstyle-results.xml
            -Dsonar.java.binaries=target/test-classes/com/visualpathit/account

  BUILD_AND_PUBLISH:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Update application.properties file
        run: 
          sed -i "s/^jdbc.username.*$/jdbc.username\=${{ secrets.RDS_USER }}/" src/main/resources/application.properties
          sed -i "s/^jdbc.username.*$/jdbc.username\=${{ secrets.RDS_PASS }}/" src/main/resources/application.properties
          sed -i "s/db01/${{ secrets.RDS_ENDPOINT }}" src/main/resources/application.properties 
      
      - name: upload image to ECR
        uses: appleboy/docker-ecr-action@master
        with:
         access_key: ${{ secrets.aws_access_key_id }}
         secret_key: ${{ secrets.aws_secret_access_key }}
         registry: ${{ secrets.REGISTRY  }}
         repo: ecsdeploy
         region: ap-south-1
         auto_tag: true
         daemon_off: false
         dockerfile: ./Dockerfile
         context: ./    
 


