name: Hprofile actions by anand 
on: workflow_dispatch

jobs: 
  Testing:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout Code
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Maven test
        run: mvn test
        
      - name: Run Checkstyle
        run: mvn checkstyle:checkstyle

      # # Step 4: Setup SonarQube
      # - name: Setup SonarQube
      #   uses: warchant/setup-sonar-scanner@v7

      # # Step 5: Run SonarQube Analysis
      # - name: SonarQube Scan
      #   run: sonar-scanner
      #       -Dsonar.host.url=${{ secrets.SONAR_URL }} 
      #       -Dsonar.login=${{ secrets.SONAR_TOKEN }} 
      #       -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} 
      #       -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} 
      #       -Dsonar.sources=src/
      #       -Dsonar.junit.reportPaths=target/surefire-reports/
      #       -Dsonar.jacoco.reportPaths=target/jacoco.exec
      #       -Dsonar.java.checkstyle.reportsPaths=target/checkstyle-results.xml
      #       -Dsonar.java.binaries=target/test-classes/com/visualpathit/account
