name: Hprofile Actions
on: workflow_dispatch

jobs: 
  Testing:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout Code
      - name: Code checkout
        uses: actions/checkout@v4

      # Step 2: Set up Java (BEFORE running Maven)
      - name: Set Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # Step 3: Build & Test the Code
      - name: Build and Compile Java Code
        run: mvn clean compile

      - name: Run Unit Tests
        run: mvn test

      - name: Run Checkstyle
        run: mvn checkstyle:checkstyle

      # Step 4: Setup SonarQube
      - name: Setup SonarQube
        uses: warchant/setup-sonar-scanner@v7

      # Step 5: Run SonarQube Analysis
      - name: SonarQube Scan
        run: |
          sonar-scanner \
            -Dsonar.host.url=${{ secrets.SONAR_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
            -Dsonar.sources=src/main/java \
            -Dsonar.tests=src/test/java \
            -Dsonar.junit.reportPaths=target/surefire-reports \
            -Dsonar.java.binaries=target/classes \
            -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml
